### PR TITLE
Fix blink SessionDetail is blinking when favorite button clicked

### LINKED ISSUE #549: Fix blink when favorite in session detail
## Kind (Required)

- Other

 ## Overview (Required)

- The title says everything.
- Probably it is occurred by [here](https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt#L208)

### PR DESCRIPTION
**Pull request by gen0083**
## Issue
- close #549 

## Overview (Required)
- Blinking was triggered that checking lineCount after setText (see figure1).
- This PR changes checking lineCount before setText
- and fix SpeakerItem equals method

figure1
figure1: slow motion

but at some points, there is a room of improve:

- ellipsis position is not exact same before situation (I think it is difficult to detect exact position before `setText`)
- It seems be better to split to CustomView such a draw logic

## Links
-

## Screenshot
Before | After
:--: | :--:
before_ellipsis_position | after_ellipsis_position
before | after

### CODE REVIEW

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt [hunk 1]
```diff
@@ -277,6 +280,15 @@ class SessionDetailFragment : DaggerFragment() {
         }, builderAction)
     }
 
+    private fun computeLineCount(fullText: String): Int {
```
Comment (jmatsu) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt]: We should use `TextUtils#ellipsize` or `measureText` to detect this.

`TextUtils#ellipsize` can ellipsize the given text actually so it's really reliable.
`getTextBounds` rounds values but `measureText` can treat values as float, so measureText has higher accuracy.

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt [hunk 2]
```diff
@@ -277,6 +280,15 @@ class SessionDetailFragment : DaggerFragment() {
...
+        if (binding.sessionDescription.width == 0) return 0
+        val rect = Rect()
+        val paint = Paint()
+        paint.textSize = binding.sessionDescription.textSize
+        paint.getTextBounds(fullText, 0, fullText.length, rect)
+        return rect.width() / binding.sessionDescription.width
```
Comment (jmatsu) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt]: We should add +1 line to return # of lines to be rendered

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt (hunk 1 above)
Comment (jmatsu) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt]: I prefer TextUtils#ellipsize because of https://github.com/DroidKaigi/conference-app-2019/pull/595/files#diff-a45d9aed66a757a483bc9cdf2b196c9aR251

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeakerItem.kt [hunk 3]
```diff
@@ -71,7 +71,7 @@ class SpeakerItem @AssistedInject constructor(
         other as SpeakerItem
 
         if (speaker != other.speaker) return false
-        if (query == null || other.query == null || query != other.query) return false
+        if (query != other.query) return false
```
Comment (jmatsu) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeakerItem.kt]: It seems `query == null && other.query == null` should be false in the previous code but this doesn't. Is it okay?

Comment (gen0083) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeakerItem.kt]: Previous code was wrong. Because GroupAdapter updated SpeakerItem even if it have same contents. (SpeakerItem looked blinking with the previous code)

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt (hunk 1 above)
Comment (gen0083) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt]: Wow, I don't know such methods, thank you! 👍 
I'll improve it 💪

**Comment by gen0083** [comment]
@jmatsu I apologize for misunderstanding.　🙇 
compute line count was not needed...

but using `TextUtils.ellipsize` is a good idea and it resolves another issue of displaying ellipsis text.
(It can be confirmed by opening the English session details screen)

another_issue

I'll fix it by another PR using `TextUtils.ellipsize` after this PR merged.
(or do it in this PR?)

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt [hunk 4]
```diff
@@ -234,20 +232,22 @@ class SessionDetailFragment : DaggerFragment() {
         }
     }
 
-    private fun setupSessionDescription() {
+    private fun setupSessionDescription(fullText: String) {
         val textView = binding.sessionDescription
         textView.doOnPreDraw {
+            // check the number of lines if set full length text (this text is not displayed yet)
+            textView.text = fullText
```
Comment (jmatsu) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt]: 👀

**Comment by jmatsu** [comment]
> I'll fix it by another PR using TextUtils.ellipsize after this PR merged.

Sure, please! 🆒
