### PR TITLE
Fix audience filter

### LINKED ISSUE #572: Filtering sessions by Audience Category = "Unspecified" (指定無し) is not working
**Overview (Required)**
- Audience Category = "Unspecified" (指定無し) filter is not working
- Even if that filter is enabled, "For Beginners" sessions are listed

**Steps To Reproduce**

1. Launch the app
2. Show session filters and enable "Unspecified" (指定無し) filter in "Audience Category" section
3. Check updated session list on Day1

**Expected behavior**
After step 3, "For Beginners" (初心者向け) sessions are filtered and not displayed on the session list.

**Actual behavior**
After step 3, All sessions including "For Beginners" (初心者向け) are listed on the session list. 

**Screenshots**
 

**Env:**
 - Device: Android Emulator
 - OS: 9.0
 - App Version or the branch: master 540ac369ce008faf69260b037a5a60e0ca8ce333

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by yh1224**
## Issue
- close #572

## Overview (Required)
- Pick sessions forBeginners when Beginners checked.
- Pick sessions *not* forBeginners when Unspecified checked.

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

File: model/src/commonMain/kotlin/Filters.kt [hunk 1]
```diff
@@ -32,11 +32,13 @@ data class Filters(
             }
         }
         val audienceCategoryFilterOk = run {
-            if (audienceCategories.contains(AudienceCategory.BEGINNERS)) {
-                session.forBeginners
+            if (audienceCategories.isEmpty()) return@run true
```
Comment (jmatsu) [inline model/src/commonMain/kotlin/Filters.kt]: 👍

File: model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt [hunk 2]
```diff
@@ -111,4 +111,45 @@ class FiltersTest {
 
         assertFalse { Filters(audienceCategories = mutableSetOf(audienceCategory)).isPass(speechSession) }
     }
+
+    private fun speechSessionMock(isBeginner: Boolean = false): SpeechSession {
```
Comment (jmatsu) [inline model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt]: So nice! 🆒
