### PR TITLE
Fix to hide BottomAppBar when session detail can not scroll

### LINKED ISSUE #153: BottomAppBar does not disappear on session details that can not be scrolled
## Overview (Required)
- BottomAppBar does not disappear on session details that can not be scrolled

image

### PR DESCRIPTION
**Pull request by androhi**
## Issue
- close #153 

## Overview (Required)
- Added SessionBottomAppBarBehavior class
- If screen be able not to scrolled, it makes to slide the bottom app bar

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionBottomAppBarBehavior.kt [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+) : BottomAppBar.Behavior(context, attrs) {
+
+    private var state: Int = STATE_SCROLLED_UP
+
+    override fun onInterceptTouchEvent(
+        parent: CoordinatorLayout,
+        child: BottomAppBar,
+        ev: MotionEvent
+    ): Boolean {
+        if (child.isShown.not() || ev.action != MotionEvent.ACTION_DOWN) {
```
Comment (takahirom) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionBottomAppBarBehavior.kt]: We can discuss in the issue. But Currently, We are using `!` instead of `.not()` 🙏

Comment (androhi) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionBottomAppBarBehavior.kt]: I see! Thanks for your review.

Comment (androhi) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionBottomAppBarBehavior.kt]: fixed! 5c9b771

**Comment by takahirom** [comment]
I confirm that! It works perfectly! Thanks 👍
