### PR TITLE
Fixed that about screen app version is not correct app version

### LINKED ISSUE #476: About screen app version is not correct app version
## Kind (Required)

- Other

 ## Overview (Required)

- It is not the app version. just strings.xml
- We should Add app version to versions.kts and use it in about/build.gradle 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/res/values/strings.xml#L12

### PR DESCRIPTION
**Pull request by kirimin**
## Issue
- close #476

## Overview (Required)
- define versionName and versionCode to Versions.kts
- use it to build.gradle and about screen

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by panpanini** [comment]
👀

File: feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutItem.kt [hunk 1]
```diff
@@ -10,7 +10,8 @@ import io.github.droidkaigi.confsched2019.about.databinding.ItemAboutBinding
 
 class AboutItem(
     @StringRes private val name: Int,
-    @StringRes private val description: Int,
+    @StringRes private val description: Int? = null,
```
Comment (panpanini) [inline feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutItem.kt]: is there a reason to keep both `description` and `descriptionString` ?

File: buildSrc/src/main/java/dependencies/Versions.kt [hunk 2]
```diff
@@ -3,4 +3,11 @@ package dependencies
 private object Versions {
     val androidCompileSdkVersion = 28
     val androidMinSdkVersion = 21
+
+    private val versionMajor = 1
+    private val versionMinor = 0
+    private val versionPatch = 0
+    val androidvVersionCode = versionMajor * 10000 + versionMinor * 100 + versionPatch
```
Comment (panpanini) [inline buildSrc/src/main/java/dependencies/Versions.kt]: it looks like maybe a typo 👀 should it be `androidVersionCode` instead?

File: buildSrc/src/main/java/dependencies/Versions.kt [hunk 3]
```diff
@@ -3,4 +3,11 @@ package dependencies
...
+
+    val androidvVersionName = "1.0.0"
```
Comment (panpanini) [inline buildSrc/src/main/java/dependencies/Versions.kt]: also this should be `androidVersionName` 👍

File: feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt [hunk 4]
```diff
@@ -46,10 +48,16 @@ class AboutSection @Inject constructor(
...
-                    description = R.string.about_version_name,
+                    descriptionString = activity.getVersionName(),
                     isLektonCheckText = true
                 )
             )
         )
     }
+
+    private fun Context.getVersionName() = try {
+        packageManager.getPackageInfo(packageName, 0).versionName
```
Comment (panpanini) [inline feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt]: instead of getting from `PackageManager`, what about [adding it to strings using `resValue`](https://www.tanelikorri.com/tutorial/android/set-variables-in-build-gradle/)?

File: buildSrc/src/main/java/dependencies/Versions.kt (hunk 2 above)
Comment (kirimin) [reply buildSrc/src/main/java/dependencies/Versions.kt]: OMG, Sorry!
I fixed it!

File: feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt (hunk 4 above)
Comment (kirimin) [reply feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt]: That great!
Thank you for advice!!

File: buildSrc/src/main/java/dependencies/Versions.kt [hunk 5]
```diff
@@ -3,4 +3,11 @@ package dependencies
 private object Versions {
     val androidCompileSdkVersion = 28
     val androidMinSdkVersion = 21
+
+    private val versionMajor = 1
+    private val versionMinor = 0
+    private val versionPatch = 0
+    val androidVersionCode = versionMajor * 10000 + versionMinor * 100 + versionPatch
+
+    val androidVersionName = "1.0.0"
```
Comment (panpanini) [inline buildSrc/src/main/java/dependencies/Versions.kt]: ah, sorry I missed it before! what about using the versionMajor/minor/patch here as well?
``` kotlin
val androidVersionName = "$versionMajor.$versionMinor.$versionPatch"
```

Comment (kirimin) [reply buildSrc/src/main/java/dependencies/Versions.kt]: Awesome💕

**Comment by kirimin** [comment]
Thank you for Reviewing!!
