### PR TITLE
Fix crash bug in highlighting text

### LINKED ISSUE #768: Search crashes when type '+' to serch bar
**Overview (Required)**
- When type + to search bar, it crushes because it is not correct Regex.

**Steps To Reproduce**

1. Go to 'Search' page
2. Type '+'
3. App crushes

**Expected behavior**
Do not crush

**Screenshots**

**Env:**
 - Device: Pixel2 XL emulator
 - OS: 8.1.0
 - master

**Additional context**
None

### PR DESCRIPTION
**Pull request by tsuyosh**
## Issue
- close #768

## Overview (Required)
- Quote input `highlightText` with `Pattern.quote()`

## Links
- https://docs.oracle.com/javase/jp/8/docs/api/java/util/regex/Pattern.html#quote-java.lang.String-

### CODE REVIEW

**Comment by tomoya0x00** [comment]
👀

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/TextViewBinding.kt [hunk 1]
```diff
@@ -20,7 +20,8 @@ fun setHighlightText(view: TextView, highlightText: String?) {
         view.text = stringBuilder
         return
     }
-    val pattern = Pattern.compile(highlightText, Pattern.CASE_INSENSITIVE)
+    val quotedHighlightText = Pattern.quote(highlightText)
```
Comment (tomoya0x00) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/bindingadapter/TextViewBinding.kt]: 📝
