### PR TITLE
Fix build androidTest, but all tests are empty yet.

### LINKED ISSUE #234: Can't run connectedAndroidTest
## Overview (Required)

I tried run androidTest (`./gradlew connectedAndroidTest`) but I got error like below. 🤔 

```bash
/Users/toshihiroyagi/ghq/github.com/sys1yagi/conference-app-2019/data/db/src/androidTest/java/io/github/droidkaigi/confsched2019/ui/ExampleInstrumentedTest.java:4: エラー: パッケージandroidx.testは存在しません
import androidx.test.InstrumentationRegistry;
                    ^
```

## Links

none

### PR DESCRIPTION
**Pull request by sys1yagi**
## Issue

- close #234

## Overview (Required)

Fix `./gradlew connectedDebugAndroidTest` 

## Links

none

## Screenshot

none

### CODE REVIEW

File: feature/about/src/androidTest/java/io/github/droidkaigi/confsched2019/widget/ExampleInstrumentedTest.java [hunk 1]
```diff
@@ -20,6 +20,6 @@ public void useAppContext() {
         // Context of the app under test.
         Context appContext = InstrumentationRegistry.getTargetContext();
 
-        assertEquals("io.github.droidkaigi.confsched2019.ui.test", appContext.getPackageName());
+        assertEquals("io.github.droidkaigi.confsched2019.about.test", appContext.getPackageName());
```
Comment (sys1yagi) [inline feature/about/src/androidTest/java/io/github/droidkaigi/confsched2019/widget/ExampleInstrumentedTest.java]: Package declaration may be incorrect?
Should I fix AndroidManifest for each module to "io.github.droidkaigi.confsched2019"?

**Comment by takahirom** [comment]
👀

File: feature/about/src/androidTest/java/io/github/droidkaigi/confsched2019/widget/ExampleInstrumentedTest.java (hunk 1 above)
Comment (takahirom) [reply feature/about/src/androidTest/java/io/github/droidkaigi/confsched2019/widget/ExampleInstrumentedTest.java]: Thank you for changing this!
If you change Manifest.xml, it will be an error that BuildCondig is duplicated in the release build, so you should not change it.

**Comment by takahirom** [comment]
LGTM :100:
