### PR TITLE
Fix SessionsItemDecoration not to draw unexpected time text

### LINKED ISSUE #324: Unexpected time text appears on session list when toggling fav status
## Overview (Required)

- On session list, when changing session favorite status, unexpected time text can appear for a moment
- This issue can be always reproduced if
  - the time frame has multiple session AND
  - change favorite status of the session listed last in the time frame

svid_20190109_223459_1

## Steps to reproduce

1. Launch app
2. On "Day1" session list, scroll to the "Unit test for ViewModel and LiveData" session
3. Click the favorite button of the session

## Expected behavior

- After step 3, there is no update about session time display

## Actual behavior

- After step 3, time text "11:20" appears on the left of the session even though another "11:20" text exists above

### PR DESCRIPTION
**Pull request by kafumi**
## Issue
- close #324

### Cause of the issue

- Time texts on session list are drawn by `SessionsItemDecoration`
- `SessionsItemDecoration` processes `RecyclerView`'s children ordered by index

```kotlin
        var lastTime: String? = null
        for (i in 0 until parent.childCount) {
            val view = parent.getChildAt(i)
            val position = parent.getChildAdapterPosition(view)
            if (position == -1 || position >= groupAdapter.itemCount) return

            val time = getSessionTime(position) ?: continue

            if (lastTime == time) continue
            lastTime = time
```

- It skips drawing text if the session time of **previous view** is same
- However, view index order and item position order can be different in RecyclerView
  - i.e. Drawing text should be skipped if the session time of **previous item** (not of previous view) is same
- Although they are luckily matched in most cases, updating item can cause the "unmatched" situation because it adds new View without recycling
  - In that case, `if (lastTime == time)` in above code doesn't work expectedly

### Solution

- Sort `RecyclerView`'s children by item position before processing
  - After this sort, we can assume `lastTime` has the time of previous position items
- Note: We can NOT remove `lastTime` usage by, for example, following code
  - It's because we need to make sure previous position item is in the visible range of `RecyclerView` to skip drawing text
    - If previous item is not visible, the time text has not been drawn. Text drawing shouldn't skip
  - Although following code performs comparison with previous item as expected, it doesn't assure previous item is in `RecyclerView`'s visible range

```kotlin
            val time = getSessionTime(position) ?: continue

            val prevItemTime = getSessionTime(position - 1)
            if (prevItemTime == time) continue
```

## Links
N/A

## Screenshot
Before | After
:--: | :--:
svid_20190109_223459_1 | svid_20190109_233031_1

### CODE REVIEW

**Comment by takahirom** [comment]
Sorry, I’m gonna go to bed now. 💤

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt [hunk 1]
```diff
@@ -42,16 +46,24 @@ class SessionsItemDecoration(
         }
     }
 
+    // Keep SparseArray instance on property to avoid object creation in every onDrawOver()
+    private val positionToViews = SparseArray<View>()
```
Comment (jmatsu) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt]: `adapterPositionToViews` is preferable rather than `positionToViews` in my opinion. What do you think about it?

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt [hunk 2]
```diff
@@ -42,16 +45,24 @@ class SessionsItemDecoration(
         }
     }
 
+    // Keep SparseArray instance on property to avoid object creation in every onDrawOver()
```
Comment (jmatsu) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt]: Make sense 👍

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt (hunk 1 above)
Comment (jmatsu) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt]: It seems other `private val` fields are above `public val`. Could you please sort fields? 👀

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt [hunk 3]
```diff
@@ -5,7 +5,11 @@ import android.content.res.Resources
 import android.graphics.Canvas
 import android.graphics.Color
 import android.graphics.Paint
+import android.util.SparseArray
+import android.util.SparseIntArray
```
[the remark this answers is not in the document]
Comment (kafumi) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt]: Fixed and squashed to d554a67c71f6b0ab43090e3b4f82e2ae2ab050a4.

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt [hunk 4]
```diff
@@ -42,16 +46,24 @@ class SessionsItemDecoration(
...
+    private val positionToViews = SparseArray<View>()
+
     override fun onDrawOver(c: Canvas, parent: RecyclerView, state: RecyclerView.State) {
-        var lastTime: String? = null
+        // Sort child views by adapter position
         for (i in 0 until parent.childCount) {
             val view = parent.getChildAt(i)
             val position = parent.getChildAdapterPosition(view)
-            if (position == -1 || position >= groupAdapter.itemCount) return
+            if (position != -1 && position < groupAdapter.itemCount) {
```
[the remark this answers is not in the document]
Comment (kafumi) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt]: Fixed as suggested at 49e58360076432e53ecdbe3c73ea12f9a77e780c.

File: feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt (hunk 1 above)
Comment (kafumi) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt]: Included both suggestion at 49e58360076432e53ecdbe3c73ea12f9a77e780c.

**Comment by kafumi** [comment]
@jmatsu Thank you for the review. I've addressed all suggestions. Please take a look when you have time :pray:
