### PR TITLE
Disable Crashlytics if the apk has been built on the local environment

### LINKED ISSUE #433: Disable Crashlytics if the apk has been built on the local environment
## Kind (Required)

- New feature

 ## Overview (Required)

- The current Crashlytics setting is enabled in every environment including CI, your PC, and my PC. However, we should collect only crashes from apks which have been built on CI.
- `isCI` flag is available in build.gradle, and it will be true only on CI environment.

 ## Links	

-

### PR DESCRIPTION
**Pull request by akihito-okada**
## Issue
- close #433

## Overview (Required)
- The current Crashlytics setting is enabled in every environment including CI, your PC, and my PC. However, we should collect only crashes from apks which have been built on CI.
- isCI flag is available in build.gradle, and it will be true only on CI environment.

### CODE REVIEW

File: frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt [hunk 1]
```diff
@@ -81,6 +81,9 @@ open class App : DaggerApplication() {
     }
 
     private fun setupCrashlytics() {
+        if (!BuildConfig.IS_BUILT_ON_CI) {
+            return
+        }
         Fabric.with(this, Crashlytics())
```
Comment (jmatsu) [inline frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt]: The approach looks correct but Crashlytics needs to be initialized anyway, and it can disable itself from the code or AndroidManifest metadata. 
Could you please use `Crashlytics.Builder#disabled` or *firebase_crashlytics_collection_enabled metadata*?

File: frontend/android/build.gradle [hunk 2]
```diff
@@ -29,6 +29,7 @@ android {
         resConfigs "ja"
         // For Android Studio Gradle sync
         applicationIdSuffix ".debug"
+        buildConfigField "boolean", "IS_BUILT_ON_CI", String.valueOf(isCi)
```
Comment (jmatsu) [inline frontend/android/build.gradle]: 👍

File: frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt (hunk 1 above)
Comment (akihito-okada) [reply frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt]: Thank you for your review. 
I got it. I will try it !

**Comment by akihito-okada** [comment]
@jmatsu 
I changed to initialize Crashlytics by firebase_analytics_collection_enabled.
Please review my change again.

**Comment by akihito-okada** [comment]
@jmatsu @takahirom 
Still have problems? If there are any problems yet, please give me feedback

File: frontend/android/src/main/AndroidManifest.xml [hunk 3]
```diff
@@ -14,7 +14,7 @@
         >
         <meta-data
             android:name="firebase_analytics_collection_enabled"
```
[the remark this answers is not in the document]
Comment (akihito-okada) [reply frontend/android/src/main/AndroidManifest.xml]: @jmatsu I'm sorry. I misunderstood about parameter names. 
And thank you for your advice. 
I modified source code again and checked whether or not Crashlytics is disabled from LogCat.
Please confirm it.

File: frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt [hunk 4]
```diff
@@ -28,7 +26,6 @@ open class App : DaggerApplication() {
     override fun onCreate() {
         super.onCreate()
 
-        setupCrashlytics()
```
Comment (jmatsu) [inline frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt]: I didn't know CrashlyticsInitProvider could initialize itself automatically.
